{{- if and .Values.webapp.podDisruptionBudget.enabled (gt (int .Values.webapp.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app.fullname" . }}-{{ .Values.webapp.component }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.webapp.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.fullname" . }}-{{ .Values.webapp.component }}
{{- end }}